bboard/bboard/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
from .views import BBLoginView
from .views import BBLogoutView

urlpatterns = [
   path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
   path('admin/', admin.site.urls),
   path('', include('main.urls', namespace='')),
   path('accounts/login', BBLoginView.as_view(), name='login'),
]

if settings.DEBUG:
   urlpatterns.append(path('static/<path:path>', never_cache(serve)))

bboard/main/urls.py
from django.urls import path
from .views import index
from .views import other_page
from .views import profile


app_name = 'main'

urlpatterns = [
   path('accounts/profile/', profile, name='profile'),
   path('<str:page>/', other_page, name='other'),
   path('', index, name='index')
]

bboard/main/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True,
                                       verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(default=True,
                                        verbose_name='Оповещать при новых комментариях?')

    class Meta(AbstractUser.Meta):
        pass

bboard/main/views.py
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required


def index(request):
   return render(request, 'main/index.html')
def other_page(request, page):
   try:
       template = get_template('main/' + page + '.html')
   except TemplateDoesNotExist:
       raise Http404
   return HttpResponse(template.render(request=request))
class BBLoginView(LoginView):
   template_name = 'main/login.html'

   @login_required
   def profile(request):
       return render(request, 'main/profile.html')
class BBLogoutView(LoginRequiredMixin, LogoutView):
   template_name = 'main/logout.html'

bboard/main/templates/layout/basic.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
   <title>{% block title %} Главная {% endblock %} - Электронная доска объявлений </title>
</head>
<body>
<div class="container-fluid">
 <div class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3  bg-white border-bottom box-shadow">

   <h5 class="mr-md-auto p-2">Электронная доска объявлений</h5>

   {% if user.is_authenticated %}
   <div class="nav-item dropdown">
       <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">Профиль</a>
       <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'main:profile' %}">Мои объявления</a>
           <a class="dropdown-item" href="#">Изменить личные данные</a>
           <a class="dropdown-item" href="#">Изменить пароль</a>
           <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a>
           <div class="dropdown-divider"></div>
           <a class="dropdown-item" href="#">Удалить</a>
       </div>
   </div>
   {% else %}
   <a class="p-2 text-dark" href="#">Регистрация</a>
   <a class="p-2 text-dark" href="{% url 'main:login' %}">Вход</a>
   {% endif %}
<a class="nav-link root" href="{% url 'main:other' page='about' %}">О сайте</a>
     </div>



   <div class="row">

       <nav class="col-md-auto nav flex-column">
           <a class="nav-link root" href="{% url 'main:index'  %}">Главная</a>
           <span class="nav-link root font-weight-bold">
               Недвижимость
           </span>
           <a class="nav-link" href="#">Жилье</a>
           <a class="nav-link" href="#">Скалады</a>
           <a class="nav-link" href="#">Квартиры</a>

           <span class="nav-link root font-weight-bold">
               Транспорт
           </span>
           <a class="nav-link" href="#">Автомобили</a>
           <a class="nav-link" href="#">Мото</a>
           <a class="nav-link" href="#">Велосипеды</a>
       </nav>

       <div class="container">
       {% bootstrap_messages %}
       {% block content %}
       {% endblock %}
       </div>

   </div>

   <footer class="mt-3 border-top">
       <small class="p-2"> &copy; Методическое пособие: Знакомство с фреймворком
           Django. 2018-2019
       </small>
   </footer>
</div>
<a class="nav-link root" href="{% url 'main:other' page='about' %}">О сайте</a>

</body>
</html>

bboard/main/templates/main/about.html
{% extends "layout/basic.html" %}

{% block title %}О сайте{% endblock %}

{% block content %}
   <h2>О сайте</h2>
   <p>Этот сайт предназначен для публикации электронных объявлений</p>
   <p>Все права оформлены и охраняются законом РФ</p>
{% endblock %}

bboard/main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}
   <h2>Последние 10 объявлений</h2>
{% endblock %}

bboard/main/templates/main/login.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Вход {% endblock %}

{% block content %}
   <h2>Вход</h2>
   {% if user.is_authenticated %}
       <p>Вы уже выполнили вход.</p>
   {% else %}
       <form method="post">
           {% csrf_token %}
           {% bootstrap_form form layout='horizontal' %}
           <input type="hidden" name="next" value="{{ next }}">
           {% buttons submit='Войти' %} {% endbuttons %}
       </form>
   {% endif %}
{% endblock %}

bboard/main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %} Выход {% endblock %}

{% block content %}
   <h2>Выход</h2>
   <p>Вы успешно вышли с сайта.</p>
{% endblock %}

bboard/main/templates/main/profile.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Профиль пользователя {% endblock %}

{% block content %}
   <h2>Профиль пользователя {{ user.username }}</h2>
   {% if user.first_name and user.last_name %}
       <p>Здравствуйте, {{ user.first_name }} {{ user.last_name }} </p>
   {% else %}
       <p>Здравствуйте! </p>
   {% endif %}
   <h3>Ваши объявления</h3>
{% endblock %}